# Generated by Django 3.2.5 on 2022-05-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcessRecord',
            new_name='AccessRecord',
        ),
    ]
